<?php
    return [
        'search' => 'Поиск',
        'actions' => 'Действия',
        'settings' => 'Настройки',
        'notFound' => 'Ничего не найдено',
        'concept' => 'Концепция',
        'core' => 'Ядро',
        'utilities' => 'Утилиты',
        'navigation' => 'Навигация',
        'components' => 'Компоненты',
        'smart components' => 'Умные компоненты',
        'russian' => 'Русский',
        'dark' => 'Тема: тёмная',
        'off' => 'Выкл',
        'on' => 'Вкл',
        'wide' => 'Широкий формат',
        'text size' => 'Размер текста',
        'reduced' => 'Уменьшенный',
        'default' => 'По умолчанию',
        'increased' => 'Увеличенный',
        'edit article' => 'Редактировать статью',
        'report a bug' => 'Сообщить об ошибке',
        'previous' => 'Назад',
        'next' => 'Далее',
    ];
