<?php
    return [
        'title' => 'Требования и установка',
        'order' => 3,
        'menu' => [
            'trebovaniya-bitrix-moduli-simai-property-i-vspomogatelnye' => 'Требования (Bitrix, модули simai.property и вспомогательные)',
            'ustanovka-modulya-simai-framework-i-aktivaciya-shablona' => 'Установка модуля simai.framework и активация шаблона',
            'fajlovaya-struktura-modul-shablon-dannye-sajta' => 'Файловая структура: модуль, шаблон, данные сайта',
            'proverka-pervogo-zapuska' => 'Проверка первого запуска',
            'struktura-frejmvorka' => 'Структура фреймворка',
            'karta-modulnoj-chasti' => 'Карта модульной части',
            'sistemnyj-shablon-i-adaptaciya' => 'Системный шаблон и адаптация',
            'sloj-dannyh-site-dir-simai-data' => 'Слой данных `{site_dir}/simai.data`',
            'komponenty-simai-kratkie-naznacheniya' => 'Компоненты SIMAI (краткие назначения)',
            'wizard-actions-perechen-i-naznacheniya' => 'Wizard actions (перечень и назначения)',
            'spravochnik-wizard-actions-sf4' => 'Справочник Wizard actions SF4',
            'ui-flou-dejstviya-interaktiv-i-navigaciya-mastera' => 'UI/флоу действия (интерактив и навигация мастера)',
            'rabota-s-katalogami-i-fajlami' => 'Работа с каталогами и файлами',
            'dannye-konfiguracii-perenos-parametrov-import-eksport-v-fajly' => 'Данные/конфигурации (перенос параметров, импорт/экспорт в файлы)',
            'infobloki-i-tipy-infoblokov' => 'Инфоблоки и типы инфоблоков',
            'nastrojki-bitrix-gruppy-korotkie-ssylki' => 'Настройки Bitrix, группы, короткие ссылки',
            'sajty-i-urlrewrite' => 'Сайты и urlrewrite',
            'chto-nuzhno-utochnit-chtoby-zakryt-dyry-v-dokumentacii-actions' => 'Что нужно уточнить, чтобы закрыть “дыры” в документации actions',
            'etalonnye-scenarii-mastera-mini-recepty' => 'Эталонные сценарии мастера: мини-рецепты',
            '1-import-infoblokov-svedenij-iblock-import-archive-sveden' => '1\) Импорт инфоблоков “сведений”: `iblock.import.archive.sveden`',
            '2-raskladka-fajlov-resheniya-file-copy-chasto-ryadom-replace-code' => '2\) Раскладка файлов решения: `file.copy` (+ часто рядом `replace.code`)',
            '3-pravila-chpu-prepare-urlrewrite-urlrewrite-add' => '3\) Правила ЧПУ: `prepare.urlrewrite` \+ `urlrewrite.add`',
            '2-skleivayuschih-shablona-scenariev-mastera' => '2 “склеивающих” шаблона сценариев мастера',
            'assety-yadra-i-konfigi-assetov-shriftov' => 'Ассеты ядра и конфиги ассетов/шрифтов',
        ],
    ];
