<?php
    return [
        'title' => 'Трек A — Решения',
        'order' => 1,
        'menu' => [
            'index' => 'Обзор',
            'intro' => 'Введение',
            'getting-started' => 'Быстрый старт',
            'installation' => 'Установка',
            'file-model' => 'Файловая модель',
            'framework-structure' => 'Структура фреймворка',
            'page-lifecycle' => 'Жизненный цикл страницы',
            'settings' => 'Настройки',
            'grid' => 'Грид',
            'blocks' => 'Блоки',
            'components' => 'Компоненты',
            'properties' => 'Свойства',
            'templates' => 'Шаблоны',
            'data-layer' => 'Data layer',
            'assets-fonts' => 'Ассеты и шрифты',
            'wizard' => 'Мастер',
            'admin-tools' => 'Админ-инструменты',
            'integrations' => 'Интеграции',
            'perf-cache' => 'Производительность и кеш',
            'debug' => 'Отладка',
            'localization' => 'Локализация',
            'security' => 'Безопасность',
            'examples' => 'Примеры',
            'solution-package' => 'Пакет решения',
            'faq' => 'FAQ',
            'troubleshooting' => 'Траблшутинг',
        ],
    ];
